CREATE TABLE `mob_usuarios` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `usuario` varchar(255) NOT NULL,
  `login` varchar(255) NOT NULL,
  `pass` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `idioma` varchar(2) NOT NULL DEFAULT 'en',
  `puntos_edificios` int(11) NOT NULL DEFAULT '0',
  `puntos_entrenamientos` int(11) NOT NULL DEFAULT '0',
  `puntos_tropas` int(11) NOT NULL DEFAULT '0',
  `baneado` tinyint(1) NOT NULL DEFAULT '0',
  `last_online` datetime DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE KEY `usuario` (`usuario`),
  UNIQUE KEY `login` (`login`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mob_entrenamientos` (
  `id_entrenamiento` int(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` int(11) NOT NULL,
  `rutas` int(11) NOT NULL DEFAULT '0',
  `encargos` int(11) NOT NULL DEFAULT '0',
  `extorsion` int(11) NOT NULL DEFAULT '0',
  `administracion` int(11) NOT NULL DEFAULT '0',
  `contrabando` int(11) NOT NULL DEFAULT '0',
  `espionaje` int(11) NOT NULL DEFAULT '0',
  `seguridad` int(11) NOT NULL DEFAULT '0',
  `proteccion` int(11) NOT NULL DEFAULT '0',
  `combate` int(11) NOT NULL DEFAULT '0',
  `armas` int(11) NOT NULL DEFAULT '0',
  `tiro` int(11) NOT NULL DEFAULT '0',
  `explosivos` int(11) NOT NULL DEFAULT '0',
  `guerrilla` int(11) NOT NULL DEFAULT '0',
  `psicologico` int(11) NOT NULL DEFAULT '0',
  `quimico` int(11) NOT NULL DEFAULT '0',
  `honor` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_entrenamiento`),
  UNIQUE KEY `id_usuario` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mob_tropas` (
  `id_tropa` int(11) NOT NULL AUTO_INCREMENT,
  `id_edificio` int(11) NOT NULL,
  `maton` int(11) NOT NULL DEFAULT '0',
  `portero` int(11) NOT NULL DEFAULT '0',
  `acuchillador` int(11) NOT NULL DEFAULT '0',
  `pistolero` int(11) NOT NULL DEFAULT '0',
  `ocupacion` int(11) NOT NULL DEFAULT '0',
  `espia` int(11) NOT NULL DEFAULT '0',
  `porteador` int(11) NOT NULL DEFAULT '0',
  `cia` int(11) NOT NULL DEFAULT '0',
  `fbi` int(11) NOT NULL DEFAULT '0',
  `transportista` int(11) NOT NULL DEFAULT '0',
  `tactico` int(11) NOT NULL DEFAULT '0',
  `francotirador` int(11) NOT NULL DEFAULT '0',
  `asesino` int(11) NOT NULL DEFAULT '0',
  `ninja` int(11) NOT NULL DEFAULT '0',
  `demoliciones` int(11) NOT NULL DEFAULT '0',
  `mercenario` int(11) NOT NULL DEFAULT '0',
  `ilegal` int(11) NOT NULL DEFAULT '0',
  `centinela` int(11) NOT NULL DEFAULT '0',
  `policia` int(11) NOT NULL DEFAULT '0',
  `guardaespaldas` int(11) NOT NULL DEFAULT '0',
  `guardia` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_tropa`),
  UNIQUE KEY `id_edificio` (`id_edificio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mob_habitaciones` (
  `id_habitacion` int(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` int(11) NOT NULL,
  `id_edificio` int(11) NOT NULL,
  `oficina` int(11) NOT NULL DEFAULT '1',
  `escuela` int(11) NOT NULL DEFAULT '0',
  `armeria` int(11) NOT NULL DEFAULT '0',
  `municion` int(11) NOT NULL DEFAULT '0',
  `cerveceria` int(11) NOT NULL DEFAULT '0',
  `taberna` int(11) NOT NULL DEFAULT '0',
  `contrabando` int(11) NOT NULL DEFAULT '0',
  `almacenArm` int(11) NOT NULL DEFAULT '0',
  `deposito` int(11) NOT NULL DEFAULT '0',
  `almacenAlc` int(11) NOT NULL DEFAULT '0',
  `caja` int(11) NOT NULL DEFAULT '0',
  `campo` int(11) NOT NULL DEFAULT '0',
  `seguridad` int(11) NOT NULL DEFAULT '0',
  `torreta` int(11) NOT NULL DEFAULT '0',
  `minas` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_habitacion`),
  UNIQUE KEY `id_edificio` (`id_edificio`),
  KEY `id_usuario` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mob_edificios` (
  `id_edificio` int(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` int(11) NOT NULL,
  `coord1` int(11) NOT NULL,
  `coord2` int(11) NOT NULL,
  `coord3` int(11) NOT NULL,
  `recursos_arm` int(11) NOT NULL DEFAULT '1000',
  `recursos_mun` int(11) NOT NULL DEFAULT '1000',
  `recursos_dol` int(11) NOT NULL DEFAULT '1000',
  `recursos_alc` int(11) NOT NULL DEFAULT '1000',
  `puntos` int(11) NOT NULL DEFAULT '0',
  `last_update` datetime NOT NULL,
  PRIMARY KEY (`id_edificio`),
  UNIQUE KEY `coords` (`coord1`,`coord2`,`coord3`),
  KEY `id_usuario` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
